; Exercise 1-15

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

; a. How many times is the procedure p applied when (sine 12.15) is evaluated?

(define (p2 x)
  (write-line (list 'p2 x))
  (- (* 3 x) (* 4 (cube x))))
(define (sine2 angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p2 (sine2 (/ angle 3.0)))))

(sine2 12.15)

;; (p2 4.9999999999999996e-2)
;; (p2 .1495)
;; (p2 .4351345505)
;; (p2 .9758465331678772)
;; (p2 -.7895631144708228)
;; ;Value: -.39980345741334

;Answer: 5 times


; b. What is the order of growth in space and number of steps (as a function of
;    a) used by the process generated by the sine procedure when (sine a) is
;    evaluated?


;; It's *roughly* O(1+log(n)) or O(log(n)) for number of steps.  

;; Space is roughly (some constant)*(number of steps)
;; which is O(C*log(n)), or O(log(n))